// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.5.1
// source: serverclidn.proto

package serverclidn

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Chunk struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NombreLibro string `protobuf:"bytes,1,opt,name=nombreLibro,proto3" json:"nombreLibro,omitempty"`
	TotalPartes string `protobuf:"bytes,2,opt,name=totalPartes,proto3" json:"totalPartes,omitempty"`
	Parte       string `protobuf:"bytes,3,opt,name=parte,proto3" json:"parte,omitempty"`
	Datos       []byte `protobuf:"bytes,4,opt,name=datos,proto3" json:"datos,omitempty"`
}

func (x *Chunk) Reset() {
	*x = Chunk{}
	if protoimpl.UnsafeEnabled {
		mi := &file_serverclidn_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Chunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Chunk) ProtoMessage() {}

func (x *Chunk) ProtoReflect() protoreflect.Message {
	mi := &file_serverclidn_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Chunk.ProtoReflect.Descriptor instead.
func (*Chunk) Descriptor() ([]byte, []int) {
	return file_serverclidn_proto_rawDescGZIP(), []int{0}
}

func (x *Chunk) GetNombreLibro() string {
	if x != nil {
		return x.NombreLibro
	}
	return ""
}

func (x *Chunk) GetTotalPartes() string {
	if x != nil {
		return x.TotalPartes
	}
	return ""
}

func (x *Chunk) GetParte() string {
	if x != nil {
		return x.Parte
	}
	return ""
}

func (x *Chunk) GetDatos() []byte {
	if x != nil {
		return x.Datos
	}
	return nil
}

type Message struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Body string `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
}

func (x *Message) Reset() {
	*x = Message{}
	if protoimpl.UnsafeEnabled {
		mi := &file_serverclidn_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_serverclidn_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_serverclidn_proto_rawDescGZIP(), []int{1}
}

func (x *Message) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

var File_serverclidn_proto protoreflect.FileDescriptor

var file_serverclidn_proto_rawDesc = []byte{
	0x0a, 0x11, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x63, 0x6c, 0x69, 0x64, 0x6e, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x63, 0x6c, 0x69, 0x64, 0x6e,
	0x22, 0x77, 0x0a, 0x05, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x12, 0x20, 0x0a, 0x0b, 0x6e, 0x6f, 0x6d,
	0x62, 0x72, 0x65, 0x4c, 0x69, 0x62, 0x72, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b,
	0x6e, 0x6f, 0x6d, 0x62, 0x72, 0x65, 0x4c, 0x69, 0x62, 0x72, 0x6f, 0x12, 0x20, 0x0a, 0x0b, 0x74,
	0x6f, 0x74, 0x61, 0x6c, 0x50, 0x61, 0x72, 0x74, 0x65, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x50, 0x61, 0x72, 0x74, 0x65, 0x73, 0x12, 0x14, 0x0a,
	0x05, 0x70, 0x61, 0x72, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x70, 0x61,
	0x72, 0x74, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x64, 0x61, 0x74, 0x6f, 0x73, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x05, 0x64, 0x61, 0x74, 0x6f, 0x73, 0x22, 0x1d, 0x0a, 0x07, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x32, 0x86, 0x01, 0x0a, 0x09, 0x43, 0x68, 0x61,
	0x74, 0x43, 0x6c, 0x69, 0x44, 0x6e, 0x12, 0x36, 0x0a, 0x08, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x61,
	0x44, 0x4e, 0x12, 0x12, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x63, 0x6c, 0x69, 0x64, 0x6e,
	0x2e, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x1a, 0x14, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x63,
	0x6c, 0x69, 0x64, 0x6e, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x00, 0x12, 0x41,
	0x0a, 0x11, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x73, 0x44, 0x69, 0x72, 0x65, 0x63, 0x63, 0x69, 0x6f,
	0x6e, 0x65, 0x73, 0x12, 0x14, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x63, 0x6c, 0x69, 0x64,
	0x6e, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x1a, 0x14, 0x2e, 0x73, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x63, 0x6c, 0x69, 0x64, 0x6e, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22,
	0x00, 0x42, 0x0f, 0x5a, 0x0d, 0x2e, 0x3b, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x63, 0x6c, 0x69,
	0x64, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_serverclidn_proto_rawDescOnce sync.Once
	file_serverclidn_proto_rawDescData = file_serverclidn_proto_rawDesc
)

func file_serverclidn_proto_rawDescGZIP() []byte {
	file_serverclidn_proto_rawDescOnce.Do(func() {
		file_serverclidn_proto_rawDescData = protoimpl.X.CompressGZIP(file_serverclidn_proto_rawDescData)
	})
	return file_serverclidn_proto_rawDescData
}

var file_serverclidn_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_serverclidn_proto_goTypes = []interface{}{
	(*Chunk)(nil),   // 0: serverclidn.Chunk
	(*Message)(nil), // 1: serverclidn.Message
}
var file_serverclidn_proto_depIdxs = []int32{
	0, // 0: serverclidn.ChatCliDn.ChunkaDN:input_type -> serverclidn.Chunk
	1, // 1: serverclidn.ChatCliDn.ChunksDirecciones:input_type -> serverclidn.Message
	1, // 2: serverclidn.ChatCliDn.ChunkaDN:output_type -> serverclidn.Message
	1, // 3: serverclidn.ChatCliDn.ChunksDirecciones:output_type -> serverclidn.Message
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_serverclidn_proto_init() }
func file_serverclidn_proto_init() {
	if File_serverclidn_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_serverclidn_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Chunk); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_serverclidn_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Message); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_serverclidn_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_serverclidn_proto_goTypes,
		DependencyIndexes: file_serverclidn_proto_depIdxs,
		MessageInfos:      file_serverclidn_proto_msgTypes,
	}.Build()
	File_serverclidn_proto = out.File
	file_serverclidn_proto_rawDesc = nil
	file_serverclidn_proto_goTypes = nil
	file_serverclidn_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ChatCliDnClient is the client API for ChatCliDn service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ChatCliDnClient interface {
	ChunkaDN(ctx context.Context, in *Chunk, opts ...grpc.CallOption) (*Message, error)
	ChunksDirecciones(ctx context.Context, in *Message, opts ...grpc.CallOption) (*Message, error)
}

type chatCliDnClient struct {
	cc grpc.ClientConnInterface
}

func NewChatCliDnClient(cc grpc.ClientConnInterface) ChatCliDnClient {
	return &chatCliDnClient{cc}
}

func (c *chatCliDnClient) ChunkaDN(ctx context.Context, in *Chunk, opts ...grpc.CallOption) (*Message, error) {
	out := new(Message)
	err := c.cc.Invoke(ctx, "/serverclidn.ChatCliDn/ChunkaDN", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatCliDnClient) ChunksDirecciones(ctx context.Context, in *Message, opts ...grpc.CallOption) (*Message, error) {
	out := new(Message)
	err := c.cc.Invoke(ctx, "/serverclidn.ChatCliDn/ChunksDirecciones", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ChatCliDnServer is the server API for ChatCliDn service.
type ChatCliDnServer interface {
	ChunkaDN(context.Context, *Chunk) (*Message, error)
	ChunksDirecciones(context.Context, *Message) (*Message, error)
}

// UnimplementedChatCliDnServer can be embedded to have forward compatible implementations.
type UnimplementedChatCliDnServer struct {
}

func (*UnimplementedChatCliDnServer) ChunkaDN(context.Context, *Chunk) (*Message, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ChunkaDN not implemented")
}
func (*UnimplementedChatCliDnServer) ChunksDirecciones(context.Context, *Message) (*Message, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ChunksDirecciones not implemented")
}

func RegisterChatCliDnServer(s *grpc.Server, srv ChatCliDnServer) {
	s.RegisterService(&_ChatCliDn_serviceDesc, srv)
}

func _ChatCliDn_ChunkaDN_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Chunk)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatCliDnServer).ChunkaDN(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/serverclidn.ChatCliDn/ChunkaDN",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatCliDnServer).ChunkaDN(ctx, req.(*Chunk))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatCliDn_ChunksDirecciones_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Message)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatCliDnServer).ChunksDirecciones(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/serverclidn.ChatCliDn/ChunksDirecciones",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatCliDnServer).ChunksDirecciones(ctx, req.(*Message))
	}
	return interceptor(ctx, in, info, handler)
}

var _ChatCliDn_serviceDesc = grpc.ServiceDesc{
	ServiceName: "serverclidn.ChatCliDn",
	HandlerType: (*ChatCliDnServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ChunkaDN",
			Handler:    _ChatCliDn_ChunkaDN_Handler,
		},
		{
			MethodName: "ChunksDirecciones",
			Handler:    _ChatCliDn_ChunksDirecciones_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "serverclidn.proto",
}
